### ISSUE TITLE
Failed to invoke clarifai2.dto.model.output_info.UnknownOutputInfo() with no args

### ISSUE THREAD

**Issue by ayushman999** [Clarifai/clarifai-java#68]
Everything was working fine but after showing the result in a few seconds the app crashes and I get this error. Please help!
![image (1)](https://user-images.githubusercontent.com/55322319/89742024-db366e00-dab3-11ea-8acd-4c73f6619bd5.png)

![image](https://user-images.githubusercontent.com/55322319/89742020-cce85200-dab3-11ea-9c41-20b51a1c8c9c.png)

**Comment by rok-clarifai** [comment]
Without the code it's not possible to say what the problem is. 

However, there were some some backend changes done related to the face model which may have caused this. Generally, the recommendation is to upgrade to the [new Clarifai gRPC Java library](https://github.com/Clarifai/clarifai-java-grpc) which is going to stay in sync with the backend changes, and provide all the latest available features.

**Comment by ayushman999** [comment]
Ok, I will try to use the upgraded library.
